#!/usr/bin/env python3
# generate_stats.py

import re
import json
from html import unescape
import os
import sys

INDEX_PATH = "index.html"
OUT_DIR = "stats"
JS_VAR = "AUTHOR_COUNTS"

# Author Counts

html = open(INDEX_PATH, encoding="utf-8").read()

pattern = re.compile(r'<a\s+[^>]*href=["\'](?:[^"\']*?/)?authors/[^"\']+["\'][^>]*>\s*(.*?)\s*\(\s*(\d+)\s*\)\s*</a>', flags=re.IGNORECASE | re.DOTALL)

rows = []

for m in pattern.finditer(html):
    raw_name = m.group(1)
    count = int(m.group(2))
    name = unescape(re.sub(r'<[^>]+>', '', raw_name)).strip()
    rows.append((name, count))

if not rows:
    print("⚠️ No author rows found with the pattern. Check index.html structure.", file=sys.stderr)
    sys.exit(1)

labels = [r[0] for r in rows]
data = [r[1] for r in rows]
export = {"labels": labels, "data": data, "raw": [{"author": n, "count": c} for n, c in rows]}

os.makedirs(OUT_DIR, exist_ok=True)
json_path = os.path.join(OUT_DIR, "author_counts.json")
with open(json_path, "w", encoding="utf-8") as fh:
    json.dump(export, fh, ensure_ascii=False, indent=2)
print("Wrote", json_path)

js_path = os.path.join(OUT_DIR, "author_counts.js")
with open(js_path, "w", encoding="utf-8") as fh:
    fh.write("// Auto-generated by extract_author_counts.py\n")
    fh.write(f"const {JS_VAR} = ")
    json.dump(export, fh, ensure_ascii=False)
    fh.write(";\n")
print("Wrote", js_path)